name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Install peer dependencies
        run: |
          npm install karma@^6.0.0
          npm install chai@^4.1.2
          npm install ajv@^8.0.0
          npm install react@18.2.0
      - name: Add node_modules/.bin to PATH
        run: echo 'PATH="$PATH:./node_modules/.bin"' >> $GITHUB_ENV
      - name: Ensure Karma is installed
        run: ls -l node_modules/.bin/
      - name: Run Karma tests
        run: npm run test
        env:
          PATH: ${{ env.PATH }}:./node_modules/.bin
